import type {
  FileScanResult,
  RuleSeverity,
} from "@src/SDK/majik-file-scanner/majik-file-scanner";

// ─── Risk band colors ─────────────────────────────────────────────────────────
export const RISK_BAND_COLOR: Record<
  NonNullable<FileScanResult["riskBand"]>,
  string
> = {
  clean: "#10b981",
  low_risk: "#84cc16",
  moderate_risk: "#f59e0b",
  high_risk: "#ef4444",
  critical_risk: "#dc2626",
};

export const RISK_BAND_BG: Record<
  NonNullable<FileScanResult["riskBand"]>,
  string
> = {
  clean: "rgba(16, 185, 129, 0.08)",
  low_risk: "rgba(132, 204, 22, 0.08)",
  moderate_risk: "rgba(245, 158, 11, 0.08)",
  high_risk: "rgba(239, 68, 68, 0.08)",
  critical_risk: "rgba(220, 38, 38, 0.1)",
};

export const RISK_BAND_LABEL: Record<
  NonNullable<FileScanResult["riskBand"]>,
  string
> = {
  clean: "Clean",
  low_risk: "Low Risk",
  moderate_risk: "Moderate Risk",
  high_risk: "High Risk",
  critical_risk: "Critical Risk",
};

export const SEVERITY_ICON: Record<RuleSeverity, string> = {
  danger: "❌",
  critical: "⛔",
  high: "🔴",
  medium: "🟡",
  low: "🔵",
  info: "⚪",
};

export const SEVERITY_COLOR: Record<RuleSeverity, string> = {
  danger: "#f70606",
  critical: "#dc2626",
  high: "#ef4444",
  medium: "#f59e0b",
  low: "#6366f1",
  info: "#6b7280",
};

export const SEVERITY_ORDER_DISPLAY: RuleSeverity[] = [
  "danger",
  "critical",
  "high",
  "medium",
  "low",
  "info",
];

export const FILE_ICONS: Record<string, string> = {
  "image/": "🖼️",
  "video/": "🎬",
  "audio/": "🎵",
  "text/": "📝",
  "application/pdf": "📄",
  "application/json": "📋",
  "application/zip": "🗜️",
  "application/x-7z-compressed": "🗜️",
  "application/x-tar": "🗜️",
  "application/gzip": "🗜️",
  "application/x-rar": "🗜️",
  "application/vnd.openxmlformats-officedocument.wordprocessingml": "📄",
  "application/vnd.openxmlformats-officedocument.spreadsheetml": "📊",
  "application/vnd.openxmlformats-officedocument.presentationml": "📊",
  "model/": "🧊",
  "application/x-sqlite3": "🗄️",
  "application/x-msdownload": "⚙️",
  "application/x-executable": "⚙️",
  "application/epub": "📚",
  "font/": "🔤",
  "application/octet-stream": "📦",
};

// ─── MIME validation ──────────────────────────────────────────────────────────
export const ALLOWED_MIME_TYPES = new Set([
  "image/png",
  "image/jpeg",
  "image/gif",
  "image/webp",
  "image/avif",
  "image/svg+xml",
  "image/bmp",
  "image/tiff",
  "image/x-icon",
  "image/heic",
  "image/heif",
  "image/jxl",
  "image/vnd.adobe.photoshop",
  "image/x-xcf",
  "image/x-raw",
  "image/x-canon-cr2",
  "image/x-nikon-nef",
  "image/x-sony-arw",
  "video/mp4",
  "video/webm",
  "video/ogg",
  "video/quicktime",
  "video/x-msvideo",
  "video/x-matroska",
  "video/x-flv",
  "video/3gpp",
  "video/3gpp2",
  "video/mpeg",
  "video/x-ms-wmv",
  "video/mp2t",
  "video/x-m4v",
  "audio/mpeg",
  "audio/ogg",
  "audio/wav",
  "audio/webm",
  "audio/aac",
  "audio/flac",
  "audio/x-m4a",
  "audio/midi",
  "audio/x-midi",
  "audio/aiff",
  "audio/x-aiff",
  "audio/opus",
  "audio/amr",
  "audio/mp4",
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.oasis.opendocument.text",
  "application/vnd.oasis.opendocument.spreadsheet",
  "application/vnd.oasis.opendocument.presentation",
  "application/rtf",
  "text/rtf",
  "text/plain",
  "text/html",
  "text/css",
  "text/csv",
  "text/xml",
  "text/markdown",
  "text/javascript",
  "application/javascript",
  "application/typescript",
  "application/json",
  "application/xml",
  "application/yaml",
  "text/yaml",
  "application/toml",
  "application/graphql",
  "text/x-python",
  "text/x-java-source",
  "text/x-c",
  "text/x-c++",
  "text/x-csharp",
  "text/x-go",
  "text/x-rust",
  "text/x-swift",
  "text/x-kotlin",
  "text/x-ruby",
  "text/x-php",
  "text/x-sh",
  "text/x-powershell",
  "application/x-httpd-php",
  "application/x-sql",
  "text/x-lua",
  "application/zip",
  "application/x-zip-compressed",
  "application/x-rar-compressed",
  "application/x-rar",
  "application/x-7z-compressed",
  "application/x-tar",
  "application/gzip",
  "application/x-gzip",
  "application/x-bzip2",
  "application/x-xz",
  "application/x-lzip",
  "application/x-zstd",
  "application/vnd.rar",
  "application/x-msdownload",
  "application/vnd.microsoft.portable-executable",
  "application/x-msi",
  "application/x-apple-diskimage",
  "application/x-debian-package",
  "application/x-rpm",
  "application/x-sh",
  "application/x-executable",
  "application/octet-stream",
  "font/ttf",
  "font/otf",
  "font/woff",
  "font/woff2",
  "application/font-woff",
  "application/vnd.ms-fontobject",
  "model/gltf+json",
  "model/gltf-binary",
  "model/obj",
  "model/stl",
  "application/x-blender",
  "application/vnd.ms-3mfdocument",
  "application/x-fbx",
  "application/postscript",
  "application/x-indesign",
  "video/x-adobe-premiere",
  "application/x-adobe-after-effects",
  "application/x-xd",
  "application/x-figma",
  "application/x-sketch",
  "application/x-affinity-designer",
  "application/x-affinity-photo",
  "application/x-vsix",
  "application/x-ipynb+json",
  "text/x-dockerfile",
  "application/x-env",
  "application/x-sqlite3",
  "application/vnd.sqlite3",
  "application/epub+zip",
  "application/x-mobipocket-ebook",
  "application/vnd.amazon.ebook",
  "application/x-abiword",
  "application/vnd.visio",
  "application/x-iwork-pages-sffpages",
  "application/x-iwork-numbers-sffnumbers",
  "application/x-iwork-keynote-sffkey",
  "application/x-pem-file",
  "application/x-pkcs12",
  "application/pkix-cert",
  "application/x-x509-ca-cert",
]);
